### ISSUE TITLE
Set variables as job outputs.

### ISSUE THREAD

**Issue by eklmv** [cardinalby/export-env-action#11]
Use case maybe too specific, but for example what if you want to use your env file to specify image for a service or any variable to be used during creation of containerized service in your ci.
You can't use same job to export env file and create service, since service will be initialized before execution of steps. Am I correct here?
So you need two jobs, one to export env file first and another depends on it and contains service. To access exported variables you need to set them as job output by hand.
Action already can set exported variables as step output, is it possible to add feature to set them as job output?
How i see it:
```.env
...
POSTGRES_IMAGE=postgres:16-alpine
...
```

```yaml
...
jobs:
  dot_env:
    ...
    steps:
      - name: checkout .env
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .env
      - name: export .env
        uses: cardinalby/export-env-action@v2
        id: export
        with:
          envFile: .env
          jobOutputs: true
    ...
  tests:
    ...
    needs: dot_env
    services:
      postgres:
        image: ${{ needs.dot_env.outputs.POSTGRES_IMAGE }}
    ...
```

**Comment by cardinalby** [comment]
Hi!

As I know, it's not possible to set job's outputs from a step without explicitly listing them in the job itself

**Comment by eklmv** [comment]
Only "workaround" i can imagine now is to save content of env file as a JSON string, that way you would need to set only one variable in outputs:
```yaml
jobs:
  dot_env:
    ...
    outputs:
        json: steps.export.outputs.json
    steps:
      - name: checkout .env
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .env
      - name: export .env
        uses: cardinalby/export-env-action@v2
        id: export
        with:
          envFile: .env
          json: true
    ...
  tests:
    ...
    needs: dot_env
    services:
      postgres:
        image: ${{ fromJSON(needs.dot_env.outputs.json)}.POSTGRES_IMAGE }}
    ...
```

**Comment by eklmv** [comment]
> Only "workaround" i can imagine now is to save content of env file as a JSON string, that way you would need to set only one variable in outputs:

As i understand it's completely doable, i will try to come up with PR for it myself, if it's okay for you maintain that feature later?

**Comment by cardinalby** [comment]
> Only "workaround" i can imagine now is to save content of env file as a JSON string, that way you would need to set only one variable in outputs

JSON approach is definitely possible, but I would put this logic inside the action only if there are no other ways to achieve it to follow kind of unix way: chaining small commands that perform well it's own task.

Try the following approach:

```yaml
jobs:
  dot_env:
    ...
    outputs:
        json: toJSON(steps.export.outputs)
    steps:
      ...
      - name: export .env
        uses: cardinalby/export-env-action@v2
        id: export
        with:
          envFile: .env
          export: false
    ...
  tests:
    ...
    needs: dot_env
    services:
      postgres:
        image: ${{ fromJSON(needs.dot_env.outputs.json)}.POSTGRES_IMAGE }}
    ...
```
