### ISSUE TITLE
Is there a way to access secrets?

### ISSUE THREAD

**Issue by fxn** [cardinalby/export-env-action#2]
Hi, is there a way to have the equivalent of

```
TOKEN=${{ secrets.TOKEN }}
```

?

**Comment by cardinalby** [comment]
You can't directly access secrets inside the actions, only pass them to steps from a workflow file.

## Option 1

You can achieve this by setting an intermediate variable for the `export-env-action` step:

```yml
- uses: cardinalby/export-env-action@v1
  id: exportStep
  with:
    envFile: 'constants.env'
  env:
    TEMP: ${{ secrets.TOKEN }}
```

__constants.env:__

```
TOKEN=${TEMP}
```

## Option 2

You can just set an env variable for the entire job without help of my action.

## Option 3. The right one!

⛔️ Don't do what you want to do! It's a vulnerable way of using your secret. When yo do it you expose your secret for the entire job. Pass the value of the secret directly to the step where it is required and nowhere else.
