### ISSUE TITLE
Not sure what I'm going incorrectly?

### ISSUE THREAD

**Issue by Altonymous** [cardinalby/export-env-action#4]
```
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: export-env-action
        uses: cardinalby/export-env-action@2.0.1
        with:
          envFile: './example.env'
```

Resulting in this error

```
Error: Error: ENOENT: no such file or directory, open './example.env'
```

The file is in the root of my repository.
